baseURL = "https://jasonliang.js.org/"
languageCode = "en-ca"
title = "Jason Liang"
googleAnalytics = "UA-156434015-1"

[params]
  author = "Jason Liang"
  description = "Hi! I am Jason Liang, a Web Developer"

[markup]
  [markup.highlight]
    style = "dracula"